apiVersion: funk.knative.dev/v1alpha1
kind: Type
metadata:
  name: funk-java-spring-sdk
spec:
  template:
    # TODO .LowerFunkName is not provided
    source: "templates/type/type.java.tmpl"
    # dest: "funks/{{.LowerFunkName}}/src/main/java/{{.Path}}/{{.UpCaseTypeName}}.java"
    dest: "types/src/main/java/{{.Path}}/{{.UpCaseTypeName}}.java"   