apiVersion: funk.knative.dev/v1alpha1
kind: Type
metadata:
  name: funk-java-spring-sdk
spec:
  template:
    source: "templates/type/type.java.tmpl"
    # TODO: LowerFunkName is not provided yet. Better to gen in funks/ rather than copy in deploy?
    # dest: "funks/{{.LowerFunkName}}/src/main/java/{{.Path}}/{{.UpCaseTypeName}}.java"
    dest: "types/src/main/java/{{.Path}}/{{.UpCaseTypeName}}.java"   